server:
  port: 3001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      springdoc:
        api-docs:
          path: /api-docs
        swagger-ui:
          path: /swagger-ui.html
        info:
          title: Customer API
          description: API documentation for Customer Management Service
          version: 1.0.0



#    spring:
#      jpa:
#        properties:
#          javax.persistence.mapping-resources: classpath:query/orm.xml